name: build-dist

# define the trigger 
# on: [push, pull_request]
on: [push]

jobs:
  build-dist:
    runs-on: ${{ matrix.os }}
    env:
      # We used "docs" as directory name for our documentation, we will be referencing this later
      working-directory: ./
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      # Check out master branch
      - name: Checkout
        uses: actions/checkout@master

      # Downloads, configures and caches Node.js
      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}

      # Install all dependencies needed to build our documentation
      - name: Install dependencies
        # Referencing our docs directory here
        working-directory: ${{env.working-directory}}
        run: npm install

      # The generate command is used to invoke Nuxt static site generation
      - name: Generate
        working-directory: ${{env.working-directory}}
        run: npm run generate
      
      - name: Release
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: './dist'
          destination_repo: 'KidBrightAI/KidBrightAI.github.io'
          destination_folder: '/'
          user_email: 'listzone@hotmail.com'
          user_name: 'comdet'
          commit_message: 'release from actions'
